### ISSUE TITLE
Fix sudden bomb explosion when bomb timer still not over.

### ISSUE THREAD

**Issue by Rohan-Muslekar** [ParichayDidwania/multiplayer-shooter#2]

**Comment by ParichayDidwania** [comment]
I would need a thorough explanation on this issue. Please provide the steps to reproduce it.

**Comment by Rohan-Muslekar** [comment]
> I would need a thorough explanation on this issue. Please provide the steps to reproduce it.

Yeah sure!
1. Play 2 v 2 match.
2. During the match let the Terrorist plant the bomb in site B (Only 1 map available LOL).
3. CT players position doesn't matter in this case. after 15-20 seconds the bomb explodes.

NOTE: This is occurring randomly 2/5 matches. If you aren't able to repro then you are unlucky. Maybe re-review your code or monitor logs while I playtest.

**Comment by ParichayDidwania** [comment]
Found a bug that used to occur when the bomb was planted after the round ended (within that 5 seconds gap). Fixed it in latest commit. If you reencounter the issue, feel free to open a new issue.
