### ISSUE TITLE
Fix body teleportation and bring smooth collision 

### ISSUE THREAD

**Issue by Rohan-Muslekar** [ParichayDidwania/multiplayer-shooter#3]

**Comment by ParichayDidwania** [comment]
body teleportation won't occur in case of decent speed internet. It is preferred to use Chrome as it handles WebGL builds better in my experience. The client also interpolates the player's movements and rotation angle. Please provide a way to reproduce your issue.

**Comment by Rohan-Muslekar** [comment]
> body teleportation won't occur in case of decent speed internet. It is preferred to use Chrome as it handles WebGL builds better in my experience. The client also interpolates the player's movements and rotation angle. Please provide a way to reproduce your issue.

Hello fellow developer,
Nice to see a prompt reply. To your knowledge, I'm using 460Mbps internet speed with 5Ghz bandwidth. Aso I was using chrome browser to play the game. It would be better If you mention it on your README that this game is NOT playable on other browsers and only playable in Chrome.

**Comment by Rohan-Muslekar** [comment]
> > body teleportation won't occur in case of decent speed internet. It is preferred to use Chrome as it handles WebGL builds better in my experience. The client also interpolates the player's movements and rotation angle. Please provide a way to reproduce your issue.
> 
> Hello fellow developer, Nice to see a prompt reply. To your knowledge, I'm using 460Mbps internet speed with 5Ghz bandwidth. Aso I was using chrome browser to play the game. It would be better If you mention it on your README that this game is NOT playable on other browsers and only playable in Chrome.

![image](https://github.com/ParichayDidwania/multiplayer-shooter/assets/46225349/03cabe85-c04c-468c-9650-25030a1ca37b)

**Comment by ParichayDidwania** [comment]
@Rohan-Muslekar I have removed the web-based client as it was causing performance issues for many devices. The game now has its own executable files which will give a lot better and smoother experience than the browser. I have already tested it on low-end laptops and the difference was immense.
